#!/usr/bin/env bash
# Functions
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)  tar xjf $1      ;;
            *.tar.gz)   tar xzf $1      ;;
            *.bz2)      bunzip2 $1      ;;
            *.rar)      rar x $1        ;;
            *.gz)       gunzip $1       ;;
            *.tar)      tar xf $1       ;;
            *.tbz2)     tar xjf $1      ;;
            *.tgz)      tar xzf $1      ;;
            *.zip)      unzip $1        ;;
            *.Z)        uncompress $1   ;;
            *)          echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
ziprm () {
    if [ -f $1 ] ; then
        unzip $1
        rm $1
    else
        echo "Need a valid zipfile"
    fi
}
psgrep() {
    if [ ! -z $1 ] ; then
        echo "Grepping for processes matching $1..."
        ps aux | grep $1 | grep -v grep
    else
        echo "!! Need name to grep for"
    fi
}
grab() {
    sudo chown -R ${USER} ${1:-.}
}

watch_changes() {
    while true
        do
           ATIME=`stat -c %Z $1`

           if [[ "$ATIME" != "$LTIME" ]]
           then
               echo "$2"
               $2
               LTIME=$ATIME
           fi
           sleep 5
    done
}
